### ISSUE TITLE
collector日志采集报错

### ISSUE THREAD

**Issue by Summerdies** [didi/nightingale#225]
日志样例：
2020-06-22 14:04:23,915 [nioEventLoopGroup-3-2] ERROR c.m.r.n.h.RequestFilterChannelHandler - Connection reset by peer
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_192]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_192]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_192]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_192]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_192]

collector错误日志：
2020-06-22 14:24:20.835853 ERROR worker/worker.go:189 [worker][file:/flume1//server.log][num:10][id:2][producer error][sid:348] : cannot get timestamp:[sname:log.xx][sid:348][timeFormat:2006-01-02 15:04:05]

这种错误是预期的么，因为错误日志后面必然跟着 详细详情，现在collector会判断不符合时间格式而抛错。

**Comment by UlricQin** [comment]
数据采集到了么？如果数据采集到了，就忽略吧

**Comment by Summerdies** [comment]
> 数据采集到了么？如果数据采集到了，就忽略吧

这个有个问题，如果我监控关键字为 exception 的话，会采集不到。一般 exception类的消息 都不会和时间在一行

**Comment by UlricQin** [comment]
你这个提议不错 @710leo 琢磨琢磨看看可以搞么

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
