### ISSUE TITLE
monapi启动panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zhaoge77** [didi/nightingale#326]
**What happened**:monapi启动时发生panic，日志如下：
[n9e@n9e monapi]$ cat  stdout.log
monapi start, use configuration file: 
runner.Cwd: /home/n9e
runner.Hostname: n9e
2020/10/08 00:59:03 http_server.go:50: starting http server, listening on: 0.0.0.0:8006
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x986256]

goroutine 57 [running]:
github.com/didi/nightingale/src/models.(*Node).LeafIds(0x0, 0x4, 0xc000370cb0, 0x1, 0x1, 0x0)
	/home/n9e/src/n9e/src/models/node.go:423 +0x26
github.com/didi/nightingale/src/models.GetLeafNidsForMon(0x2d, 0x0, 0x0, 0x0, 0xc00017ca28, 0x1, 0x0, 0x0, 0x0)
	/home/n9e/src/n9e/src/models/node.go:579 +0x132
github.com/didi/nightingale/src/modules/monapi/scache.syncStras()
	/home/n9e/src/n9e/src/modules/monapi/scache/stra.go:56 +0x803
github.com/didi/nightingale/src/modules/monapi/scache.SyncStras()
	/home/n9e/src/n9e/src/modules/monapi/scache/stra.go:15 +0x43
created by github.com/didi/nightingale/src/modules/monapi/scache.Init
	/home/n9e/src/n9e/src/modules/monapi/scache/init.go:27 +0x10a

[n9e@n9e monapi]$ cat WARNING.log
2020-10-08 00:59:03.587028 WARNING report/report.go:97 curl http://192.168.1.2:8006/api/hbs/instances?mod=judge&alive=1 fail: Get "http://192.168.1.2:8006/api/hbs/instances?mod=judge&alive=1": dial tcp 192.168.1.2:8006: connect: connection refused
2020-10-08 00:59:03.587071 WARNING scache/init.go:39 get judge err:Get "http://192.168.1.2:8006/api/hbs/instances?mod=judge&alive=1": dial tcp 192.168.1.2:8006: connect: connection refused
2020-10-08 00:59:03.587430 WARNING report/report.go:97 curl http://192.168.1.2:8006/api/hbs/instances?mod=judge&alive=1 fail: Get "http://192.168.1.2:8006/api/hbs/instances?mod=judge&alive=1": dial tcp 192.168.1.2:8006: connect: connection refused
2020-10-08 00:59:03.587494 WARNING scache/judge.go:26 get judge err:Get "http://192.168.1.2:8006/api/hbs/instances?mod=judge&alive=1": dial tcp 192.168.1.2:8006: connect: connection refused
2020-10-08 00:59:03.835946 WARNING scache/stra.go:84 get node err:empty circle &{1 cpu使用率大于88% 1 4 null 120 120 1 [{"eopt":"\u003e=","func":"all","metric":"cpu.util","params":[],"threshold":88}] [] 00:00 23:59 [0,1,2,3,4,5,6] [36000,1] 3  null null zhangsan 2020-10-07 21:55:34 +0800 CST zhangsan 2020-10-07 21:55:34 +0800 CST 0 {"users":[],"groups":[],"duration":60,"level":1} null  [] [] [{>= all cpu.util [] 88}] [] [0 1 2 3 4 5 6] [36000 1] [] [] [96 57 60 95 97 25 66 91 98 100 47 48 101 49 59 102 43 69 70 74 90 94 67 107 26 42 68 85 28 54 61 73 103 93 63 77 84 105 113 24 27 39 44 51 56 109 55 87 99 106 82 65 89 108 38 52 71 75 83] [192.168.1.2] {[] [] 60 1}  []}
2020-10-08 00:59:04.059427 WARNING scache/stra.go:84 get node err:empty circle &{2 cpu使用率大于95% 1 4 null 120 120 1 [{"eopt":"\u003e=","func":"all","metric":"cpu.util","params":[],"threshold":95}] [] 00:00 23:59 [0,1,2,3,4,5,6] [36000,1] 2  null null zhangsan 2020-10-07 21:55:34 +0800 CST zhangsan 2020-10-07 21:55:34 +0800 CST 0 {"users":[],"groups":[],"duration":60,"level":1} null  [] [] [{>= all cpu.util [] 95}] [] [0 1 2 3 4 5 6] [36000 1] [] [] [51 103 43 59 71 84 97 26 68 54 25 93 102 113 66 27 82 95 105 106 28 48 83 85 107 47 38 39 98 24 99 101 108 63 74 90 94 60 61 67 70 73 42 56 57 69 77 44 52 55 65 75 87 91 96 49 100 109 89] [192.168.1.2] {[] [] 60 1}  []}
2020-10-08 00:59:04.284299 WARNING scache/stra.go:84 get node err:empty circle &{3 机器loadavg大于16 1 4 null 300 120 1 [{"eopt":"\u003e","func":"all","metric":"cpu.loadavg.1","params":[],"threshold":16}] [] 00:00 23:59 [0,1,2,3,4,5,6] [36000,1] 2  null null zhangsan 2020-10-07 21:55:34 +0800 CST zhangsan 2020-10-07 21:55:34 +0800 CST 0 {"users":[],"groups":[],"duration":60,"level":1} null  [] [] [{> all cpu.loadavg.1 [] 16}] [] [0 1 2 3 4 5 6] [36000 1] [] [] [47 61 65 71 38 44 109 54 73 93 105 56 69 97 55 94 103 77 101 100 57 99 70 28 42 39 67 87 24 25 75 90 96 43 52 74 84 113 51 59 48 63 107 108 89 106 83 95 102 26 68 60 66 82 85 91 98 27 49] [192.168.1.2] {[] [] 60 1}  []}
2020-10-08 00:59:04.504877 WARNING scache/stra.go:84 get node err:empty circle &{4 某磁盘无法正常读写 1 4 null 60 120 1 [{"eopt":"\u003e","func":"all","metric":"disk.rw.error","params":[],"threshold":0}] [] 00:00 23:59 [0,1,2,3,4,5,6] [36000,1] 1  null null zhangsan 2020-10-07 21:55:34 +0800 CST zhangsan 2020-10-07 21:55:34 +0800 CST 0 {"users":[],"groups":[],"duration":60,"level":1} null  [] [] [{> all disk.rw.error [] 0}] [] [0 1 2 3 4 5 6] [36000 1] [] [] [74 107 108 42 66 73 56 68 91 97 102 109 75 77 89 25 96 71 103 83 105 28 57 63 24 85 93 60 94 26 44 59 106 52 67 69 84 39 48 65 98 99 100 43 55 61 27 47 51 87 90 101 95 38 70 82 49 54 113] [192.168.1.2] {[] [] 60 1}  []}
2020-10-08 00:59:04.726531 WARNING scache/stra.go:84 get node err:empty circle &{5 主机时间同步状态异常 1 4 null 180 120 1 [{"eopt":"\u003e","func":"all","metric":"sys.ntp.offset.ms","params":[],"threshold":1000}] [] 00:00 23:59 [0,1,2,3,4,5,6] [36000,1] 3  null null zhangsan 2020-10-07 21:55:34 +0800 CST zhangsan 2020-10-07 21:55:34 +0800 CST 0 {"users":[],"groups":[],"duration":60,"level":1} null  [] [] [{> all sys.ntp.offset.ms [] 1000}] [] [0 1 2 3 4 5 6] [36000 1] [] [] [106 108 26 42 56 93 99 44 71 73 98 48 83 91 54 55 59 38 89 43 82 95 47 66 77 49 69 94 27 85 103 70 97 24 39 51 25 100 96 60 63 75 105 61 84 90 52 113 67 68 74 87 101 28 57 65 102 107 109] [192.168.1.2] {[] [] 60 1}  []}
2020-10-08 00:59:04.950616 WARNING scache/stra.go:84 get node err:empty circle &{6 监控agent失联 1 4 null 120 120 1 [{"eopt":"=","func":"nodata","metric":"proc.agent.alive","params":[],"threshold":0}] [] 00:00 23:59 [0,1,2,3,4,5,6] [36000,1] 1  null null zhangsan 2020-10-07 21:55:34 +0800 CST zhangsan 2020-10-07 21:55:34 +0800 CST 0 {"users":[],"groups":[],"duration":60,"level":1} null  [] [] [{= nodata proc.agent.alive [] 0}] [] [0 1 2 3 4 5 6] [36000 1] [] [] [48 75 90 28 87 97 63 57 71 73 109 52 94 101 105 106 60 47 65 69 99 26 49 54 67 70 103 107 24 74 77 39 85 100 38 83 89 95 66 84 25 56 91 96 51 82 43 42 102 55 61 68 93 98 108 113 27 59 44] [192.168.1.2] {[] [] 60 1}  []}
2020-10-08 00:59:05.177451 WARNING scache/stra.go:84 get node err:empty circle &{7 cpu使用率大于99% 1 4 null 180 120 1 [{"eopt":"\u003e=","func":"all","metric":"cpu.util","params":[],"threshold":99}] [] 00:00 23:59 [0,1,2,3,4,5,6] [36000,1] 1  null null zhangsan 2020-10-07 21:55:34 +0800 CST zhangsan 2020-10-07 21:55:34 +0800 CST 0 {"users":[],"groups":[],"duration":60,"level":1} null  [] [] [{>= all cpu.util [] 99}] [] [0 1 2 3 4 5 6] [36000 1] [] [] [73 90 108 48 43 55 113 38 67 77 102 60 99 91 96 82 24 61 25 54 84 93 97 51 83 95 39 70 63 66 87 59 103 109 44 68 100 47 69 71 89 94 65 27 42 49 75 98 101 107 26 52 56 57 74 85 105 106 28] [192.168.1.2] {[] [] 60 1}  []}
2020-10-08 00:59:05.408816 WARNING scache/stra.go:84 get node err:empty circle &{8 内存使用率大于80% 1 4 null 120 120 1 [{"eopt":"\u003e","func":"all","metric":"mem.bytes.used.percent","params":[],"threshold":80}] [] 00:00 23:59 [0,1,2,3,4,5,6] [36000,1] 2  null null zhangsan 2020-10-07 21:55:34 +0800 CST zhangsan 2020-10-07 21:55:34 +0800 CST 0 {"users":[],"groups":[],"duration":60,"level":1} null  [] [] [{> all mem.bytes.used.percent [] 80}] [] [0 1 2 3 4 5 6] [36000 1] [] [] [75 42 47 69 67 26 55 60 38 39 66 99 28 54 87 57 65 70 108 24 63 95 107 113 25 96 103 44 74 49 59 109 102 56 85 97 73 83 89 101 106 48 51 93 94 71 84 91 98 43 52 90 27 77 105 100 61 68 82] [192.168.1.2] {[] [] 60 1}  []}
2020-10-08 00:59:05.633496 WARNING scache/stra.go:84 get node err:empty circle &{9 磁盘使用率达到85% 1 4 null 300 120 1 [{"eopt":"\u003e","func":"all","metric":"disk.bytes.used.percent","params":[],"threshold":85}] [] 00:00 23:59 [0,1,2,3,4,5,6] [36000,1] 3  null null zhangsan 2020-10-07 21:55:34 +0800 CST zhangsan 2020-10-07 21:55:34 +0800 CST 0 {"users":[],"groups":[],"duration":60,"level":1} null  [] [] [{> all disk.bytes.used.percent [] 85}] [] [0 1 2 3 4 5 6] [36000 1] [] [] [106 25 39 66 91 96 103 71 93 51 55 70 95 26 43 57 67 69 102 28 59 63 107 108 113 47 89 38 48 82 98 27 49 75 105 60 77 99 101 85 94 109 68 73 83 97 52 100 54 56 74 84 42 65 90 24 44 61 87] [192.168.1.2] {[] [] 60 1}  []}
2020-10-08 00:59:05.857478 WARNING scache/stra.go:84 get node err:empty circle &{10 磁盘使用率达到88% 1 4 null 300 120 1 [{"eopt":"\u003e","func":"all","metric":"disk.bytes.used.percent","params":[],"threshold":88}] [] 00:00 23:59 [0,1,2,3,4,5,6] [36000,1] 2  null null zhangsan 2020-10-07 21:55:34 +0800 CST zhangsan 2020-10-07 21:55:34 +0800 CST 0 {"users":[],"groups":[],"duration":60,"level":1} null  [] [] [{> all disk.bytes.used.percent [] 88}] [] [0 1 2 3 4 5 6] [36000 1] [] [] [47 95 68 74 82 105 63 109 27 39 49 56 51 59 71 103 26 61 99 100 54 55 84 106 107 69 73 87 102 43 85 98 52 60 89 93 57 90 113 108 24 42 67 97 91 38 70 77 83 25 94 44 65 75 28 96 48 66 101] [192.168.1.2] {[] [] 60 1}  []}
2020-10-08 00:59:06.080402 WARNING scache/stra.go:84 get node err:empty circle &{11 磁盘使用率达到92% 1 4 null 300 120 1 [{"eopt":"\u003e","func":"all","metric":"disk.bytes.used.percent","params":[],"threshold":92}] [] 00:00 23:59 [0,1,2,3,4,5,6] [36000,1] 1  null null zhangsan 2020-10-07 21:55:34 +0800 CST zhangsan 2020-10-07 21:55:34 +0800 CST 0 {"users":[],"groups":[],"duration":60,"level":1} null  [] [] [{> all disk.bytes.used.percent [] 92}] [] [0 1 2 3 4 5 6] [36000 1] [] [] [90 89 93 27 67 69 82 83 84 25 48 60 66 97 102 51 52 61 63 24 74 109 113 54 68 77 99 100 55 105 57 103 106 26 65 71 73 96 108 44 75 98 101 39 47 49 56 59 94 70 85 91 38 42 87 28 43 95 107] [192.168.1.2] {[] [] 60 1}  []}
2020-10-08 00:59:06.303023 WARNING scache/stra.go:84 get node err:empty circle &{12 磁盘繁忙程度超过90% 1 4 null 180 120 1 [{"eopt":"\u003e","func":"all","metric":"disk.io.util","params":[],"threshold":90}] [{"tkey":"mount","topt":"=","tval":["/"]}] 00:00 23:59 [0,1,2,3,4,5,6] [36000,1] 3  null null zhangsan 2020-10-07 21:55:34 +0800 CST zhangsan 2020-10-07 21:55:34 +0800 CST 0 {"users":[],"groups":[],"duration":60,"level":1} null  [] [] [{> all disk.io.util [] 90}] [{mount = [/]}] [0 1 2 3 4 5 6] [36000 1] [] [] [26 67 97 107 43 55 91 85 90 93 25 57 60 49 51 98 103 38 39 48 89 100 27 63 73 47 82 113 52 65 69 61 87 42 108 109 28 56 105 59 75 77 99 101 102 74 95 96 66 84 106 24 44 54 68 70 83 71 94] [192.168.1.2] {[] [] 60 1}  []}
2020-10-08 00:59:06.527751 WARNING scache/stra.go:84 get node err:empty circle &{13 端口挂了 1 4 null 60 120 1 [{"eopt":"!=","func":"all","metric":"proc.port.listen","params":[],"threshold":1}] [] 00:00 23:59 [0,1,2,3,4,5,6] [36000,1] 2  null null zhangsan 2020-10-07 21:55:34 +0800 CST zhangsan 2020-10-07 21:55:34 +0800 CST 0 {"users":[],"groups":[],"duration":60,"level":1} null  [] [] [{!= all proc.port.listen [] 1}] [] [0 1 2 3 4 5 6] [36000 1] [] [] [63 75 91 93 94 38 51 57 61 100 24 66 82 83 84 96 26 65 67 70 39 71 73 107 49 74 101 47 48 55 97 98 42 44 102 85 27 28 59 69 43 90 25 60 77 54 103 68 99 106 95 105 108 109 113 52 56 87 89] [192.168.1.2] {[] [] 60 1}  []}

是不是2.8版本的报警策略和3.0不兼容导致。。？操作过程：从2.8版本导出报警策略，再导入3.0后，monapi出现panic

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Logs:
- Others:

**Comment by UlricQin** [comment]
rdb没有起来？

**Comment by zhaoge77** [comment]
rdb起来了，服务正常的

**Comment by UlricQin** [comment]
你的错误日志里提示的是8006端口没有起来，但是这个/api/hbs/instances应该是rdb的接口，rdb默认应该是8000，你调整了address.yml吧

**Comment by zhaoge77** [comment]
没有调整address.yml的接口，8006是monapi的端口

**Comment by UlricQin** [comment]
sql文件导入了么，n9e_hbs库有么

**Comment by zhaoge77** [comment]
> sql文件导入了么，n9e_hbs库有么

都有的，我刚才把那2条无主的报警策略手动删除之后，monapi正常起起来了。这里看是否可以对无主的报警策略加一个异常处理或者过滤处理，使之不影响服务的正常启动。

**Comment by UlricQin** [comment]
嗯，刚用手机不好看代码，刚看了一下，代码有问题，刚修复了，多谢反馈
